# LMS Project - Entropy Configuration
# Migrated from lms/scripts/entropy_check/config.py
# Usage: python -m tpb_sdk.entropy --path . --report

# Line count thresholds per file type
thresholds:
  backend: 500      # JS files in backend/
  frontend: 300     # JS files in frontend/
  css: 600          # CSS files (per module, after split)
  default: 500      # Other files

# Files/directories to ignore (extends defaults)
ignore:
  - vault-api       # Separate subproject with its own config

# Project-specific exceptions
exceptions:
  # Files allowed to have high coupling (entry points, orchestrators)
  coupling:
    - backend/index.js
    - frontend/app/index.js
  
  # Files expected to be "god files" (shared utilities by design)
  god_files:
    - backend/cors.js           # CORS config used everywhere
    - frontend/app/api.js       # API client used everywhere
    - frontend/app/state.js     # State management (by design)
  
  # Entry points that are always "used" for dead code detection
  entry_points:
    - backend/index.js
    - frontend/app/index.js
