# Vault-API Frontend - Entropy Configuration
# React/Next.js project with TPB "Dumb Front" architecture
# Usage: python -m tpb_sdk.entropy --path . --report

# Use React preset (includes Next.js thresholds)
preset: react

# Line count thresholds (override preset if needed)
thresholds:
  react_component: 150   # React components
  nextjs_entry: 50       # page.tsx, layout.tsx (very short)
  hook: 100              # Custom hooks (use*.ts)
  service: 80            # Pure fetch wrappers
  frontend: 300          # General frontend files
  css: 600               # CSS files

# Files/directories to ignore (extends defaults)
ignore:
  - .next               # Next.js build output
  - out                 # Next.js export output
  - _to_refacto         # Phase 0: legacy code being ported
  - components/ui       # shadcn/ui (generated, don't analyze)

# Project-specific exceptions
exceptions:
  # Entry points that are always "used" for dead code detection
  entry_points:
    - src/app/**/page.tsx
    - src/app/**/layout.tsx
    - src/app/**/route.tsx
  
  # Files expected to be imported by many others (god files by design)
  god_files:
    - src/contexts/index.ts          # Context barrel
    - src/components/tpb/index.ts    # TPB lib barrel
    - src/components/common/index.ts # Common components barrel
    - src/services/index.ts          # Services barrel
    - src/lib/utils.ts               # Shared utilities
  
  # Files allowed to have many imports (orchestrators)
  coupling:
    - src/app/**/layout.tsx          # Layouts import many components

# TPB Frontend Convention Checks (opt-in)
# These enforce the "Dumb Front" architecture from the init-plan
tpb_checks:
  # Detect business logic that should be in backend (front_* endpoints)
  # Flags: .filter(), .sort(), .reduce(), calculate*, compute*, etc.
  dumb_front: true
  
  # Require imports via barrel files (index.ts)
  # Flags: direct imports like '@/components/Button/Button'
  barrel_imports: true
  
  # Enforce 1 file = 1 export (TPB convention)
  # Exceptions: index.ts, types.ts, constants.ts
  single_export: true

